[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

solc_version = "0.8.25"
evm_version = "Paris"
ignored_error_codes = [
    2018, # view functions can be marked as pure
    2394, # tstore beaks composability
    3860, # contract size limit exceeded (for tests)
    5574, # contract size limit exceeded (for tests)
]

remappings = [
    "@forge-std-1.9.1=dependencies/forge-std-1.9.1/src",
    "@solady-0.0.227=dependencies/solady-0.0.227/src",
    "@openzeppelin-contracts-5.0.2=dependencies/@openzeppelin-contracts-5.0.2",
]
fs_permissions = [{ access = "read", path = "./out" }]

optimizer = true
optimizer_runs = 10_000_000
ffi = false

[profile.lite]
optimizer = false
optimizer-runs = 0
ffi = false

ignored_warnings_from = ["./tests/mocks/MockERC20.sol"]

[fuzz]
runs = 1_000

[rpc_endpoints]
sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 1, url = "https://api-sepolia.etherscan.io/api" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", chain = 421614, url = "https://api-sepolia.arbiscan.io/api" }
optimism-sepolia = { key = "${OP_ETHERSCAN_API_KEY}", chain = 11155420, url = "https://api-sepolia-optimistic.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
forge-std = "1.9.1"
solady = "0.0.227"
"@openzeppelin-contracts" = "5.0.2"
